### ISSUE TITLE
using zoom will crash

### ISSUE THREAD

**Issue by shenjackyuanjie** [sakura-ryoko/tweakeroo#48]
```text

Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "fi.dy.masa.tweakeroo.util.MiscUtils$PostKeyAction.isActive()" because "fi.dy.masa.tweakeroo.util.MiscUtils.lastZoomValue" is null
	at fi.dy.masa.tweakeroo.util.MiscUtils.onZoomDeactivated(MiscUtils.java:174)
	at fi.dy.masa.tweakeroo.config.Callbacks$KeyCallbackHotkeysGeneric.onKeyAction(Callbacks.java:446)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:170)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:276)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:178)
	at net.minecraft.class_312.handler$fek000$malilib$hookOnMouseClick(class_312.java:2558)
	at net.minecraft.class_312.method_1601(class_312.java:67)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.tweakeroo.util.MiscUtils.onZoomDeactivated(MiscUtils.java:174)
	at fi.dy.masa.tweakeroo.config.Callbacks$KeyCallbackHotkeysGeneric.onKeyAction(Callbacks.java:446)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:170)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:276)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:178)
	at net.minecraft.class_312.handler$fek000$malilib$hookOnMouseClick(class_312.java:2558)
	at net.minecraft.class_312.method_1601(class_312.java:67)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
Mixins in Stacktrace:
	fi.dy.masa.malilib.hotkeys.KeybindMulti:
		top.hendrixshen.magiclib.mixin.malilib.accessor.KeybindMultiAccessor (magiclib_legacy_compat-malilib.mixins.json)
		me.fallenbreath.tweakermore.mixins.core.gui.access.KeybindMultiAccessor (tweakermore.mixins.json)
	net.minecraft.class_312:
		fi.dy.masa.tweakeroo.mixin.MixinMouse (mixins.tweakeroo.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMouseListener (mixins.jgui.json)
		fi.dy.masa.malilib.mixin.MixinMouse (mixins.malilib.json)
		dev.architectury.mixin.fabric.client.MixinMouseHandler (architectury.mixins.json)
		io.github.reserveword.imblocker.mixin.fabric.MouseMixin (imblocker.mixins.json)
		com.replaymod.core.mixin.MixinMouse (mixins.core.replaymod.json)
		com.replaymod.recording.mixin.MixinMouseHelper (mixins.recording.replaymod.json)
		yalter.mousetweaks.fabric.mixin.MixinMouseHandler (mousetweaks-fabric.mixins.json)
		net.fabricmc.fabric.mixin.screen.MouseMixin (fabric-screen-api-v1.mixins.json)
	net.minecraft.class_1255:
		carpettisaddition.mixins.utils.ThreadExecutorAccessor (carpet-tis-addition.mixins.json)
		dynamic_fps.impl.mixin.bugfix.BlockableEventLoopMixin (dynamic_fps-common.mixins.json)
	com.mojang.blaze3d.systems.RenderSystem:
		com.replaymod.replay.mixin.MixinTileEntityEndPortalRenderer (mixins.replay.replaymod.json)
		me.jellysquid.mods.sodium.mixin.workarounds.event_loop.RenderSystemMixin (sodium.mixins.json)
		net.irisshaders.iris.mixin.statelisteners.MixinRenderSystem (mixins.iris.json)
		net.irisshaders.iris.mixin.MixinRenderSystem (mixins.iris.json)
		net.irisshaders.iris.mixin.MixinGlStateManager (mixins.iris.json)

```

`tweakeroo: Tweakeroo 0.20.999-sakura.24`

**Comment by sakura-ryoko** [comment]
This appears to be a mod conflict issue, but I can't explain further because this is not a complete log file.

**Comment by RunawayHen** [comment]
I have the same issue when zooming, even if i turn off zoom but press the hotkey in game. Here is my (i think) complete log file. Hope this helps:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-08-20 01:37:52
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "fi.dy.masa.tweakeroo.util.MiscUtils$PostKeyAction.isActive()" because "fi.dy.masa.tweakeroo.util.MiscUtils.lastZoomValue" is null
	at fi.dy.masa.tweakeroo.util.MiscUtils.onZoomDeactivated(MiscUtils.java:174)
	at fi.dy.masa.tweakeroo.util.MiscUtils.checkZoomStatus(MiscUtils.java:154)
	at fi.dy.masa.tweakeroo.event.InputHandler.onKeyInput(InputHandler.java:80)
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:153)
	at net.minecraft.class_309.handler$bhk000$malilib$onKeyboardInput(class_309.java:1121)
	at net.minecraft.class_309.method_1466(class_309.java:346)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.tweakeroo.util.MiscUtils.onZoomDeactivated(MiscUtils.java:174)
	at fi.dy.masa.tweakeroo.util.MiscUtils.checkZoomStatus(MiscUtils.java:154)
	at fi.dy.masa.tweakeroo.event.InputHandler.onKeyInput(InputHandler.java:80)
	at fi.dy.masa.malilib.event.InputEventHandler.onKeyInput(InputEventHandler.java:153)
	at net.minecraft.class_309.handler$bhk000$malilib$onKeyboardInput(class_309.java:1121)
	at net.minecraft.class_309.method_1466(class_309.java:346)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)

-- Uptime --
Details:
	JVM uptime: 1180.623s
	Wall uptime: 1156.842s
	High-res time: 1152.565s
	Client ticks: 22351 ticks / 1117.550s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['---'/22, l='ClientLevel', x=558.45, y=64.00, z=-6627.83]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,140,0), Section: (at 0,12,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 11595185 game time, 14867065 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 514

-- Last reload --
Details:
	Reload number: 3
	Reload reason: manual
	Finished: Yes
	Packs: fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, litematica, lithium, malilib, minihud, modmenu, sodium, tweakeroo, worldedit, xaerominimap, xaeroworldmap, vanilla, file/VisibleOres2.8.zip, file/Faithful 32x - 1.21.zip, file/OreHighlighter-1.0.2.zip

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Mac OS X (x86_64) version 11.7.10
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 846013368 bytes (806 MiB) / 2080374784 bytes (1984 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel HD Graphics 6000
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MiB): 1536.00
	Graphics card #0 deviceId: 0x1626
	Graphics card #0 versionInfo: Revision ID: 0x0009
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MiB): 10240.00
	Virtual memory used (MiB): 6191.53
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 772.00
	Space in storage for jna.tmpdir (MiB): available: 15208.54, total: 239172.41
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 15208.54, total: 239172.41
	Space in storage for io.netty.native.workdir (MiB): available: 15208.54, total: 239172.41
	Space in storage for java.io.tmpdir (MiB): available: 15208.54, total: 239172.41
	Space in storage for workdir (MiB): available: 15208.54, total: 239172.41
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.102.1+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b55973446a
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc6a
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a76a
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c6a
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a76a
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c6a
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b36a
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b55973446a
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.20+7f945d5b6a
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.6.0+605f22ad6a
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a76a
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+1daea2156a
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.17+16c4ae256a
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b996a
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b996a
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae066a
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd96a
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc9216a
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+780172706a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b36a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a56a
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a56a
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c6a
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b6a
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a936a
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c6a
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+650897126a
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b6a
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c6a
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c6a
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b36a
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e6a
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea2156a
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b36a
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd06a
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b16a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c76a
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b55973446a
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c6a
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.17+1db1cc1f6a
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea2156a
		fabricloader: Fabric Loader 0.16.2
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		litematica: Litematica 0.19.2
		lithium: Lithium 0.13.0
		malilib: MaLiLib 0.20.0
		minecraft: Minecraft 1.21.1
		minihud: MiniHUD 0.31.999-sakura.23
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		sodium: Sodium 0.5.11+mc1.21
		tweakeroo: Tweakeroo 0.20.999-sakura.24
		worldedit: WorldEdit 7.3.6+6892-3d660b8
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
	Launched Version: fabric-loader-0.16.2-1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Intel(R) HD Graphics 6000 GL version 4.1 INTEL-16.5.14, Intel Inc.
	Window size: 1440x900
	GFLW Platform: cocoa
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 10/10 chunks
	Resource Packs: fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, litematica, lithium, malilib, minihud, modmenu, sodium, tweakeroo (incompatible), worldedit (incompatible), xaerominimap (incompatible), xaeroworldmap (incompatible), vanilla, file/VisibleOres2.8.zip (incompatible), file/Faithful 32x - 1.21.zip, file/OreHighlighter-1.0.2.zip
	Current Language: en_us
	Locale: 
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 4x Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['--'/22, l='ServerLevel[---]', x=558.45, y=64.00, z=-6627.83]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 5407351177885160003

**Comment by Snaffothegreat** [comment]
Hello, i have found 1 possible solution to your problem, in the new revamp of the Tweakeroo zoom it crashes if it reads data from an older version of Tweakeroo. to fix this simply delete the file at .minecraft/config/tweakeroo.json and let it rewrite the config settings, however this will remove your preferences for Tweakeroo.

**Comment by RunawayHen** [comment]
> Hello, i have found 1 possible solution to your problem, in the new revamp of the Tweakeroo zoom it crashes if it reads data from an older version of Tweakeroo. to fix this simply delete the file at .minecraft/config/tweakeroo.json and let it rewrite the config settings, however this will remove your preferences for Tweakeroo.

This helped, thanks a lot! For reference I copied the .json to somewhere else before deleting it, that way I could open it via text and read my own preferences.

**Comment by Snaffothegreat** [comment]
i probably should have done that too lol

**Comment by sakura-ryoko** [comment]
I have a possible band-aid solution; but I am still not sure what other mods you guys are using that is somehow causing Tweakeroo to think that the Zoom Activate Key was pressed upon saving your config for this to even happen.  The error as reported shouldn't be able to logically happen.  It's like saying 1 + 1 can be 5; but here we are.

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/tweakeroo/releases/tag/1.21-0.21.1-sakura.1
